### ISSUE TITLE
Create a CI to test if the docs can generate from PR

### ISSUE THREAD

**Issue by esoubiran-aneo** [aneoconsulting/ArmoniK.Core#295]
This will be used to be sure from the PR that docs can be generated. This will avoid docs to failed generating in main.

@aneojgurhem, where can I put this? Have we written any recommandation about how to name files in workflows? (or do we need to do it ?)

**Comment by aneojgurhem** [comment]
We do not have recommandations to name workflows. I'm not sure if we need one as pipelines depend on the code in the repo.

**Comment by aneojgurhem** [comment]
We may have to explain what we expect in multiple required files.
- formatting
- docs
- etc..

**Comment by esoubiran-aneo** [comment]
Here the documentation with an exemple of a workflow file to enable CI for the docs.

https://aneoconsulting.github.io/armonik-docs-theme/guide/verify-generation

**Comment by aneojgurhem** [comment]
can you add it ?

**Comment by esoubiran-aneo** [comment]
Yes, I will add it if it's ok for you.
